Customer_manager/Models/Skills.cs
namespace Customer_manager.Models
{
    public class Skills
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int Value { get; set; }
        public Customer_infos? CustomerInfo { get; set; }
        public int CustomerInfoId { get; set; }
    }
}

Customer_manager/Controllers/SkillsController.cs
using Customer_manager.Models;
using Customer_manager.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Customer_manager.Controllers
{
    public class SkillsController:Controller
    {

        private readonly UserManager<Customers> _userManager;
        private readonly GenericRepository<Skills> _repository;
        private readonly ApplicationDbContext _context;

        public SkillsController(GenericRepository<Skills> repository, UserManager<Customers> userManager, ApplicationDbContext context)
        {
            _repository = repository;
            _userManager = userManager;
            _context = context;


        }

        public ActionResult Index()
        {
            // İçine Hizmetler listesini ekleyin
            var customerInfo = _repository.GetAll();

            return View(customerInfo);
        }


        [HttpGet]
        public IActionResult Create()
        {
            var model = new Skills();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(Skills entity)
        {
            if (ModelState.IsValid)
            {
                // Giriş yapan kullanıcının CustomerInfoId'sini al
                int customerInfoId = GetLoggedInCustomerInfoId();

                if (customerInfoId == 0)
                {
                    // Eğer kullanıcı bulunamazsa hata döndürülebilir
                    ModelState.AddModelError("", "Kullanıcı bilgileri bulunamadı.");
                    return View(entity);
                }

                // Hizmetler nesnesine CustomerInfoId'yi ekle
                entity.CustomerInfoId = customerInfoId;

                // Veritabanına ekle
                _repository.Insert(entity);

                return RedirectToAction("Index", "Admin");
            }

            return View(entity);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {

            var entity = _repository.GetById(id);
            return View(entity);
        }

        [HttpPost]
        public ActionResult Edit(Skills entity)
        {
            if (ModelState.IsValid)
            {
                _repository.Update(entity);
                return RedirectToAction("Index", "Admin");
            }
            return View(entity);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var entity = _repository.GetById(id);
            _repository.Delete(entity);
            return RedirectToAction("Index", "Admin");
        }



        private int GetLoggedInCustomerInfoId()
        {

            string loggedInUserName = User.Identity.Name;

            var customerInfo = _context.CustomerInfos
                .FirstOrDefault(ci => ci.Customer.CustomerKey == loggedInUserName);

            return customerInfo?.CustomerInfoId ?? 0;

        }

    }
}

Customer_manager/Views/Skills/Create.cshtml
@model Skills

@{
	Layout = "_AdminLayout";
}

<div class="row">
	<div class="col-lg-12">

		<div class="card">
			<div class="card-body">
				<h5 class="card-title">Vertical Form</h5>

				<!-- Vertical Form -->
				<form class="row g-3" method="post">
					<input type="text" asp-for="ID" class="form-control" id="inputNanme4" hidden>
					<div class="col-12">
						<label for="inputNanme4" class="form-label">Başlık</label>
						<input type="text" asp-for="Title" class="form-control" id="inputNanme4">
					</div>
					<div class="col-12">
						<label for="inputEmail4" class="form-label">Yetenek Değeri (%)</label>
						<input type="text" asp-for="Value" class="form-control" id="inputEmail4">
					</div>

					<div class="text-center">
						<button type="submit" class="btn btn-primary">Kaydet</button>
						<a href="/admin/index" class="btn btn-secondary">İptal</a>
					</div>
				</form><!-- Vertical Form -->

			</div>
		</div>


	</div>
</div>

Customer_manager/Views/Skills/Edit.cshtml
@model Skills

@{
	Layout = "_AdminLayout";
}

<div class="row">
	<div class="col-lg-12">

		<div class="card">
			<div class="card-body">
				<h5 class="card-title">Vertical Form</h5>

				<!-- Vertical Form -->
				<form class="row g-3" method="post">
					<input type="text" asp-for="ID" class="form-control" id="inputNanme4" hidden>
					<div class="col-12">
						<label for="inputNanme4" class="form-label">Başlık</label>
						<input type="text" asp-for="Title" class="form-control" id="inputNanme4">
					</div>
					<div class="col-12">
						<label for="inputEmail4" class="form-label">Yetenek Değeri (%)</label>
						<input type="text" asp-for="Value" class="form-control" id="inputEmail4">
					</div>
				
					<div class="text-center">
						<button type="submit" class="btn btn-primary">Kaydet</button>
						<a href="/admin/index" class="btn btn-secondary">İptal</a>
					</div>
				</form><!-- Vertical Form -->

			</div>
		</div>


	</div>
</div>

Customer_manager/Views/Skills/Index.cshtml
@model Customer_manager.Models.Customer_infos




@*  tabloları buraya koyabiliriz  *@
<div class="row">
    <div class="col-lg-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Yetenekler</h5>

                <!-- Default Table -->
                <table class="table">
                    <thead>
                    <th>@Html.ActionLink("Yeni Yetenek Ekle", "Create", "Skills", null, new { @class = "btn btn-success", role = "button" })</th>

                    <tr>


                        <th scope="col">Başlık</th>
                        <th scope="col">Değer</th>        
                        <th scope="col">İşlemler</th>


                    </tr>
                    </thead>
                    <tbody>
                        @foreach (var i in Model.Skills)
                        {
                            <tr>

                                <td>@i.Title</td>
                                <td>%@i.Value</td>
                              

                                <td>
                                    <div style="display: inline-block;">
                                        <a href="/skills/edit/@i.ID" class="btn btn-success">Güncelle</a>
                                    </div>
                                    <div style="display: inline-block;">
                                        <form id="deleteForm" action="/skills/delete/@i.ID" method="post">
                                            <button class="btn btn-danger" type="submit" onclick="return confirm('Silmek İstediğininze Emin misiniz?')">Sil</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        }



                    </tbody>
                </table>

                <!-- End Default Table Example -->
            </div>
        </div>

    </div>
</div>